version: '3.9'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fidesio_drupal
    ports:
      - 5500:80
    volumes:
      - .:/opt/drupal
    restart: always
  db:
    image: mariadb:10.3
    container_name: fidesio_db
    restart: always
    ports:
      - "13408:3306"
    environment:
      MYSQL_USER: fidesio
      MYSQL_PASSWORD: fidesio
      MYSQL_ROOT_PASSWORD: fidesio
      MYSQL_DATABASE: fidesio
  phpmyadmin:
    image: phpmyadmin
    platform: linux/amd64
    container_name: fidesio_pma
    links:
      - db
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 5501:80

